name: test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  flame: ^1.18.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true



  assets:
    - assets/images/
    - assets/jsons/


  fonts:
    - family: Minesweeper
      fonts:
        - asset: assets/fonts/Minesweeper-Regular.ttf